{
    "identifiers": [
        "retryableBefore",
        "fn",
        "beforeEach",
        "shouldRun",
        "shouldRun",
        "fn",
        "Cypress",
        "result",
        "result",
        "result",
        "result",
        "shouldRun"
    ],
    "literals": [
        "'test:after:run'",
        "'failed'"
    ],
    "variables": [
        "retryableBefore",
        "shouldRun"
    ],
    "comments": [
        "we use beforeEach as cypress will run this on retry attempt",
        "we just abort early if we detected that it's already run",
        "When a test fails we flip the `shouldRun` flag back to true",
        "so when cypress retries and runs the `beforeEach()` before",
        "the test that failed, we'll run the `fn()` logic once more."
    ],
    "docstrings": [
        "* A `before()` alternative that gets run when a failing test is retried.\n *\n * By default cypress `before()` isn't run when a test below it fails\n * and is retried. Because we use `before()` as a place to setup state\n * before running assertions inside `it()` this means we can't make use\n * of cypress retry functionality to make our suites more reliable.\n *\n * https://github.com/cypress-io/cypress/issues/19458\n * https://stackoverflow.com/questions/71285827/cypress-e2e-before-hook-not-working-on-retries"
    ],
    "functions": [],
    "classes": []
}