{
    "identifiers": [
        "logging",
        "movai_core_shared",
        "logger",
        "Log",
        "LogAdapter",
        "movai_core_shared",
        "exceptions",
        "MovaiException",
        "caplog",
        "expected",
        "caplog",
        "text",
        "expected",
        "caplog",
        "clear",
        "caplog",
        "should_have_trackback",
        "should_have_trackback",
        "caplog",
        "text",
        "caplog",
        "text",
        "caplog",
        "clear",
        "caplog",
        "caplog",
        "set_level",
        "logging",
        "DEBUG",
        "logger",
        "Log",
        "get_logger",
        "log",
        "addHandler",
        "caplog",
        "handler",
        "LogAdapter",
        "log",
        "log",
        "info",
        "check_log",
        "caplog",
        "logger",
        "error",
        "check_log",
        "caplog",
        "log",
        "debug",
        "check_log",
        "caplog",
        "logger",
        "warning",
        "msg",
        "check_log",
        "caplog",
        "MovaiException",
        "MovaiException",
        "e",
        "logger",
        "error",
        "e",
        "check_trackback",
        "caplog",
        "logger",
        "warning",
        "e",
        "check_trackback",
        "caplog",
        "log",
        "error",
        "e",
        "check_trackback",
        "caplog",
        "logger",
        "info",
        "check_trackback",
        "caplog",
        "logger",
        "critical",
        "breakpoint",
        "check_trackback",
        "caplog"
    ],
    "literals": [
        "\"Traceback\"",
        "\"Traceback\"",
        "\"test_logger\"",
        "\"test_logger\"",
        "\"in try log\"",
        "\"INFO     test_logger:test_logger.py:30 in try log\\n\"",
        "\"in try logger\"",
        "\"ERROR    test_logger:test_logger.py:32 [user_log:True] in try logger\\n\"",
        "\"a %s 2 %f 3 %i\"",
        "\"a\"",
        "\"DEBUG    test_logger:test_logger.py:34 a a 2 2.000000 3 3\\n\"",
        "\"message\"",
        "f\"this is a {msg}\"",
        "\"WARNING  test_logger:test_logger.py:37 [user_log:True] this is a message\\n\"",
        "\"test error\"",
        "\"test error logger\"",
        "f\"test error 2 logger e:{e}\"",
        "f\"test log error e:{e}\"",
        "\"test logger info e:{e}\"",
        "\"last\""
    ],
    "variables": [
        "log",
        "logger",
        "msg"
    ],
    "comments": [],
    "docstrings": [
        "\"\"\"help function to validate the log\"\"\"",
        "\"\"\"help function to validate the log\"\"\"",
        "\"\"\"Test for the logger that will generate new logger with get_logger\n    and test out all the different verbosity and check the logs that are correct\n    \"\"\""
    ],
    "functions": [
        "check_log",
        "check_trackback",
        "test_logger"
    ],
    "classes": []
}